name: matatabi_question_math


on:
 schedule:
    - cron:  '*/1 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy==3.10.0
#         env:
#           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#           ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
#           API_KEY: ${{ secrets.API_KEY }}
#           API_SECRET_KEY : ${{ secrets.API_SECRET_KEY }}
      - name: Run script
        run: |
          python main.py
