name: matatabi_question_math

# 実行タイミング
on:
 schedule:
   - cron: '*/1 * * * *'

# 実行内容
jobs:
  build:
    # ubuntuで実行
    runs-on: ubuntu-latest    
    # 実行する処理＆コマンド
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.12
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          # 必要なパッケージインストール
          pip install tweepy
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET_KEY : ${{ secrets.API_SECRET_KEY }}
      - name: Run script
        run: |
          # main.pyの実行
          python main.py
