name: matatabi_question_math




on:
 schedule:
    - cron:  '*/1 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy==3.10.0
        
      - name: Run script
        env:
          CS: ${{ secrets.CS }}
          CK: ${{ secrets.CK }}
          AS: ${{ secrets.AS }}
          AT: ${{ secrets.AT }}
        run: |
          python main.py
