name: CI

on: [push, pull_request]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Print Hello World
      run : echo "hello world"
    - name: Show filelist
      run : ls -la 
